server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: webchat-backend

  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/webchat
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  redis:
    host: localhost
    port: 6379
    timeout: 60000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

  rabbitmq:
    host: localhost
    port: 5672
    username: webchat
    password: webchat123

  security:
    jwt:
      secret: mySecretKeyForWebChatApplication2024
      expiration: 86400000 # 24 horas

logging:
  level:
    com.webchat: DEBUG
    org.springframework.web.socket: DEBUG
    org.springframework.security: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

app:
  cors:
    allowed-origins: http://localhost:3000,http://localhost:3001
  websocket:
    allowed-origins: http://localhost:3000,http://localhost:3001
  chat:
    max-group-size: 11
    message-history-limit: 1000

---
# Profile para desenvolvimento
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/webchat
    username: webchat
    password: webchat123

---
# Profile para produção
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}